import React from "react";
//import { directive } from "@babel/types"; // ........autogenerated
import "./card-list.styles.css";
import { Card } from "../card/card.component";

export const CardList = props => {
  //console.log(props);
  return (
    <div className="card-list">
      {/* maps over state.monsters array and returs h1 for each element */}
      {props.monsters.map(monster => (
        <Card key={monster.id} monster={monster}></Card>
      ))}
    </div>
  );
};
